# 1. Exploration et ingestion

In [37]:
import locale

import kagglehub
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

locale.setlocale(locale.LC_ALL, 'fr_FR.UTF-8')

'fr_FR.UTF-8'

In [38]:
from dotenv import load_dotenv

# Charge les variables (identifiants Kaggle) depuis le fichier .env
load_dotenv()

True

## 1.1 Chargement des données

https://www.kaggle.com/datasets/sdolezel/black-friday

In [39]:
file_name = "train.csv"

In [40]:
# téléchargement du dataset
path = kagglehub.dataset_download("sdolezel/black-friday")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\p02114\.cache\kagglehub\datasets\sdolezel\black-friday\versions\1

In [41]:
dataset_path = Path(path) / file_name

if dataset_path.exists():
    df = pd.read_csv(dataset_path)
    print("Dataset chargé avec succès.")
else:
    raise FileNotFoundError(f"""Le chemin spécifié est invalide: '{dataset_path.as_posix()}'.
        Vérifiez si le fichier a été téléchargé avec succès.""")

Dataset chargé avec succès.

In [ ]:
# Dimensions du dataset
print(f"Nombre de lignes : {df.shape[0]:n}")
print(f"Nombre de colonnes : {df.shape[1]:n}")

Nombre de lignes : 550 068
Nombre de colonnes : 12

In [45]:
df.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

## 1.2 EDA

__Features :__
- `User_ID` : ID utilisateur
- `Product_ID` : ID produit
- `Gender` : sexe de l'utilisateur
- `Age` : tranches d'âges
- `Occupation` : occupation de l'utilisateur (anonymisé)
- `City_Category` : catégorie de la ville (A, B, C - ordinal ?)
- `Stay_In_Current_City_Years` : nombre d'années passées dans la ville actuelle
- `Marital_Status` : statut marital
- `Product_Category_1` : catégorie principale du produit (anonymisé)
- `Product_Category_2` : 2ème catégorie du produit (anonymisé)
- `Product_Category_3` : 3ème catégorie du produit (anonymisé)
- `Purchase` : quantité achetée

*NB : un produit peut avoir plusieurs catégories*

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     550068 non-null  int64
 1   Product_ID                  550068 non-null  str
 2   Gender                      550068 non-null  str
 3   Age                         550068 non-null  str
 4   Occupation                  550068 non-null  int64
 5   City_Category               550068 non-null  str
 6   Stay_In_Current_City_Years  550068 non-null  str
 7   Marital_Status              550068 non-null  int64
 8   Product_Category_1          550068 non-null  int64
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64
dtypes: float64(2), int64(5), str(5)
memory usage: 50.4 MB

In [47]:
df.describe()

,User_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
count,5.500680e+05,550068.000000,550068.000000,550068.000000,376430.000000,166821.000000,550068.000000
mean,1.003029e+06,8.076707,0.409653,5.404270,9.842329,12.668243,9263.968713
std,1.727592e+03,6.522660,0.491770,3.936211,5.086590,4.125338,5023.065394
min,1.000001e+06,0.000000,0.000000,1.000000,2.000000,3.000000,12.000000
25%,1.001516e+06,2.000000,0.000000,1.000000,5.000000,9.000000,5823.000000
50%,1.003077e+06,7.000000,0.000000,5.000000,9.000000,14.000000,8047.000000
75%,1.004478e+06,14.000000,1.000000,8.000000,15.000000,16.000000,12054.000000
max,1.006040e+06,20.000000,1.000000,20.000000,18.000000,18.000000,23961.000000

In [48]:
df.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [49]:
df['Gender'].value_counts()

Gender
M    414259
F    135809
Name: count, dtype: int64